load("@rules_jvm_external//:defs.bzl", "artifact")

java_library(
    name = "platformhost",
    srcs = glob(["*.java"]),
    deps = [
        artifact("com.google.guava:guava"),
    ],
    visibility = ["//visibility:public"]
)
