load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "changelog_proto",
    srcs = ["changelog.proto"],
    visibility = ["//visibility:public"],
)

proto_library(
    name = "flags_proto",
    srcs = ["flags.proto"],
    visibility = ["//visibility:public"],
)
